trigger:
- main

pool:
  name: MyOwnAgentPool

variables:
  APP_DIR: /home/bralmeidaa/tbm/
  APP_PATTERN: "uvicorn backend.main:app"

steps:
# 1. Copiar Conteúdo da App (sem alterações)
- task: CopyFiles@2
  displayName: 'Copiar arquivos da aplicação'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      backend/**
      database/**
      requirements.txt
    TargetFolder: '$(APP_DIR)'
    OverWrite: true
    ignoreMakeDirErrors: true

# 2. Instalar dependências (sem alterações)
- script: |
    cd $(APP_DIR)
    python3 -m venv .venv
    source .venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependências Python'

# 4. Iniciar Backend EM BACKGROUND (MODIFICADO)
- script: |
    echo "Deploy concluído. Reiniciando o serviço 'tbm-app' via systemd..."
    sudo systemctl restart tbm-app.service
    
    echo "Serviço reiniciado."
  displayName: 'Reiniciar o Serviço da Aplicação'

# 5. (OPCIONAL, MAS RECOMENDADO) Verificar se a App está no ar
- script: |
    echo "Aguardando o serviço reiniciar..."
    sleep 10
    
    # Verifica o status do serviço
    sudo systemctl is-active --quiet tbm-app.service || (echo "O serviço tbm-app não está ativo!" && exit 1)

    # Tenta acessar o endpoint
    curl --fail http://localhost:8000/health || (echo "A aplicação não respondeu." && exit 1)
    
    echo "Serviço e aplicação respondendo com sucesso!"
  displayName: 'Verificar se o Serviço está Rodando'