trigger:
  - main

pool:
  name: MyOwnAgentPool

variables:
  APP_DIR: /home/bralmeidaa/tbm/

steps:
# 1. Copy App Contents
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      backend/**
      database/**
      requeriments.txt
    TargetFolder: '$(APP_DIR)'
    OverWrite: true
    ignoreMakeDirErrors: true

# 2. Install dependencies
- script: |
    cd $(APP_DIR)

    python3 -m venv .venv

    source .venv/bin/activate
    
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependências Python'

# 3. Set Env. Variables
- script: |
    echo "##vso[task.setvariable variable=BINANCE_API_KEY]$(BINANCE_API_KEY)"
    echo "##vso[task.setvariable variable=BINANCE_API_SECRET]$(BINANCE_API_SECRET)"
  displayName: 'Configurar variáveis de ambiente'

# 4. Run App (Flask/FastAPI)
- script: |
    cd $(APP_DIR)
    python -m uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
  displayName: 'Iniciar Backend'