#!/usr/bin/env python3
"""
Base class for specialized trading bots
Each bot is optimized for specific symbols and strategies
"""

import asyncio
import json
import numpy as np
import pandas as pd
from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Tuple
from datetime import datetime, timedelta
from dataclasses import dataclass
import logging

@dataclass
class BotSpecialization:
    """Configuration for bot specialization."""
    name: str
    symbols: List[str]
    strategy_type: str
    timeframes: List[str]
    max_positions: int
    risk_per_trade: float
    specialized_indicators: List[str]
    entry_conditions: Dict
    exit_conditions: Dict
    performance_targets: Dict
    notes: str

class BaseSpecializedBot(ABC):
    """Base class for all specialized trading bots."""
    
    def __init__(self, specialization: BotSpecialization):
        self.specialization = specialization
        self.name = specialization.name
        self.symbols = specialization.symbols
        self.active_positions = {}
        self.performance_history = []
        self.specialized_features = {}
        
        # Performance tracking
        self.stats = {
            'trades_total': 0,
            'trades_won': 0,
            'trades_lost': 0,
            'total_pnl': 0.0,
            'win_rate': 0.0,
            'avg_pnl_per_trade': 0.0,
            'max_drawdown': 0.0,
            'sharpe_ratio': 0.0,
            'specialization_score': 0.0
        }
        
        # Logging
        self.logger = logging.getLogger(f"SpecializedBot.{self.name}")
        
    @abstractmethod
    async def analyze_market_conditions(self, symbol: str, timeframe: str) -> Dict:
        """Analyze market conditions specific to this bot's specialization."""
        pass
    
    @abstractmethod
    async def generate_specialized_signal(self, symbol: str, timeframe: str) -> Optional[Dict]:
        """Generate trading signal using specialized logic."""
        pass
    
    @abstractmethod
    async def calculate_specialized_features(self, price_data: pd.DataFrame) -> Dict:
        """Calculate features specific to this bot's strategy."""
        pass
    
    @abstractmethod
    def validate_specialized_conditions(self, signal: Dict, market_conditions: Dict) -> Tuple[bool, str]:
        """Validate signal against specialized conditions."""
        pass
    
    async def run_specialized_cycle(self) -> List[Dict]:
        """Run one complete cycle for this specialized bot."""
        signals = []
        
        for symbol in self.symbols:
            for timeframe in self.specialization.timeframes:
                try:
                    # Analyze market conditions
                    market_conditions = await self.analyze_market_conditions(symbol, timeframe)
                    
                    # Generate specialized signal
                    signal = await self.generate_specialized_signal(symbol, timeframe)
                    
                    if signal:
                        # Validate specialized conditions
                        is_valid, reason = self.validate_specialized_conditions(signal, market_conditions)
                        
                        if is_valid:
                            signal['bot_name'] = self.name
                            signal['specialization'] = self.specialization.strategy_type
                            signal['market_conditions'] = market_conditions
                            signals.append(signal)
                            
                            self.logger.info(f"Signal generated by {self.name} for {symbol}: {signal['direction']}")
                        else:
                            self.logger.debug(f"Signal rejected by {self.name}: {reason}")
                
                except Exception as e:
                    self.logger.error(f"Error in specialized cycle for {symbol}: {e}")
        
        return signals
    
    def update_performance(self, trade_result: Dict):
        """Update bot performance metrics."""
        self.stats['trades_total'] += 1
        
        pnl = trade_result.get('pnl', 0)
        self.stats['total_pnl'] += pnl
        
        if pnl > 0:
            self.stats['trades_won'] += 1
        else:
            self.stats['trades_lost'] += 1
        
        # Calculate derived metrics
        if self.stats['trades_total'] > 0:
            self.stats['win_rate'] = self.stats['trades_won'] / self.stats['trades_total']
            self.stats['avg_pnl_per_trade'] = self.stats['total_pnl'] / self.stats['trades_total']
        
        # Update specialization score (performance relative to general market)
        self._calculate_specialization_score()
        
        # Store in history
        self.performance_history.append({
            'timestamp': datetime.now(),
            'trade_result': trade_result,
            'cumulative_stats': self.stats.copy()
        })
        
        # Keep only last 1000 trades
        if len(self.performance_history) > 1000:
            self.performance_history = self.performance_history[-1000:]
    
    def _calculate_specialization_score(self):
        """Calculate how well this bot performs in its specialization."""
        if len(self.performance_history) < 10:
            self.stats['specialization_score'] = 0.5
            return
        
        # Get recent performance
        recent_trades = self.performance_history[-20:]
        recent_pnls = [t['trade_result'].get('pnl', 0) for t in recent_trades]
        
        if not recent_pnls:
            self.stats['specialization_score'] = 0.5
            return
        
        # Calculate metrics
        win_rate = sum(1 for pnl in recent_pnls if pnl > 0) / len(recent_pnls)
        avg_pnl = np.mean(recent_pnls)
        consistency = 1 - (np.std(recent_pnls) / (abs(avg_pnl) + 0.001))
        
        # Specialization score combines win rate, profitability, and consistency
        self.stats['specialization_score'] = (win_rate * 0.4 + 
                                            min(avg_pnl * 100, 1) * 0.4 + 
                                            max(consistency, 0) * 0.2)
    
    def get_performance_summary(self) -> Dict:
        """Get comprehensive performance summary."""
        return {
            'bot_name': self.name,
            'specialization': self.specialization.strategy_type,
            'symbols': self.symbols,
            'stats': self.stats,
            'recent_performance': self.performance_history[-10:] if self.performance_history else [],
            'active_positions': len(self.active_positions),
            'last_updated': datetime.now().isoformat()
        }
    
    def should_trade(self, current_positions: int) -> bool:
        """Check if bot should trade based on position limits."""
        return current_positions < self.specialization.max_positions
    
    def get_risk_per_trade(self) -> float:
        """Get risk per trade, potentially adjusted by recent performance."""
        base_risk = self.specialization.risk_per_trade
        
        # Adjust risk based on recent performance
        if self.stats['specialization_score'] > 0.7:
            return base_risk * 1.2  # Increase risk if performing well
        elif self.stats['specialization_score'] < 0.3:
            return base_risk * 0.7  # Decrease risk if performing poorly
        
        return base_risk